"""Measure dataset coverage from the loaded warehouse and write it for the registry.

Coverage is measured, never declared: for each dataset, which utilities it has
rows for, each one's first and last date, and its row count per calendar year,
read from the tables the loaders just filled. ``services.shared.dataset_registry``
reads the file this writes; the website imports the same file. Run after a load (``load_all`` does) or alone:

    python -m db.loaders.coverage

Do not hand-edit the generated file.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import psycopg

from db.loaders import load_circuits, load_epss
from db.loaders.util import print_step
from shared.db import connect, get_settings

ROOT = Path(__file__).resolve().parents[2]
COVERAGE_PATH = ROOT / "shared" / "dataset_coverage.json"
GENERATED_NOTE = (
    "Generated by db/loaders/coverage.py from the loaded warehouse. Do not "
    "hand-edit. Regenerate with: python -m db.loaders.coverage"
)

# How to read each dataset's rows: its table, the date each row counts on (the
# column the services filter a period by), and where the utility comes from.
# ``utility`` names the utility column; ``source_utility`` is the utility whose
# published file the loader read, for a table with no utility column; neither
# means the dataset has no utility dimension.
SOURCES: dict[str, dict[str, Any]] = {
    "cpuc_ignitions": {"table": "wildfire.cpuc_ignitions", "date": "event_date", "utility": "utility"},
    "calfire_incidents": {
        "table": "wildfire.calfire_incidents",
        "date": "date_only_created",
        "utility": "utility",
    },
    "epss_outages": {
        "table": "wildfire.epss_outages",
        "date": "start_date",
        "source_utility": load_epss.SOURCE_UTILITY,
    },
    "psps_events": {
        "table": "wildfire.psps_events",
        "date": "deenergization_start_date",
        "utility": "utility",
    },
    "us_ignitions": {"table": "wildfire.us_ignitions", "date": "event_date"},
    "cpuc_ignitions_with_time": {"table": "wildfire.cpuc_ignitions_with_time", "date": "event_date"},
    "circuits": {"table": "wildfire.circuits", "source_utility": load_circuits.SOURCE_UTILITY},
}


def _span(row: tuple[Any, ...]) -> dict[str, Any]:
    first, last, rows = row
    return {
        "first": first.isoformat() if first else None,
        "last": last.isoformat() if last else None,
        "rows": int(rows),
    }


def _years(cur: psycopg.Cursor, table: str, date_col: str, where: str) -> dict[str, dict[str, int]]:
    """Rows per calendar year, keyed by the group (a utility, or "" for all rows).

    Only years with rows appear; a year that is absent has none. Rows with no
    date are left out, as they are from the span.
    """
    cur.execute(
        f"""
        SELECT {where}, extract(year FROM {date_col})::int, count(*) FROM {table}
        WHERE {date_col} IS NOT NULL
        GROUP BY 1, 2 ORDER BY 1, 2
        """
    )
    years: dict[str, dict[str, int]] = {}
    for group, year, rows in cur.fetchall():
        years.setdefault(group if group is not None else "", {})[str(year)] = int(rows)
    return years


def measure(conn: psycopg.Connection) -> dict[str, Any]:
    """Each dataset's measured date span, and its span per utility."""
    datasets: dict[str, Any] = {}
    with conn.cursor() as cur:
        for key, source in SOURCES.items():
            table = source["table"]
            date_col = source.get("date")
            span_sql = (
                f"min({date_col}), max({date_col}), count(*)"
                if date_col
                else "NULL::date, NULL::date, count(*)"
            )
            # A row with no date cannot place a count in a period, so it does
            # not extend coverage; the row count still includes it.
            cur.execute(f"SELECT {span_sql} FROM {table}")
            entry: dict[str, Any] = {"date_column": date_col, **_span(cur.fetchone())}
            # Rows per calendar year: whether rows exist in an asked period,
            # not only whether the period falls inside the span.
            entry["years"] = _years(cur, table, date_col, "''").get("", {}) if date_col else {}
            if source.get("utility"):
                column = source["utility"]
                cur.execute(
                    f"""
                    SELECT {column}, {span_sql} FROM {table}
                    WHERE {column} IS NOT NULL
                    GROUP BY 1 ORDER BY 1
                    """
                )
                entry["utility_dimension"] = True
                entry["utilities"] = {row[0]: _span(row[1:]) for row in cur.fetchall()}
                by_utility = _years(cur, table, date_col, column) if date_col else {}
                for code, span in entry["utilities"].items():
                    span["years"] = by_utility.get(code, {})
                # Rows with no utility: what an "untagged" filter can count.
                cur.execute(f"SELECT {span_sql} FROM {table} WHERE {column} IS NULL")
                untagged = _span(cur.fetchone())
                untagged["years"] = by_utility.get("", {})
                entry["untagged"] = untagged if untagged["rows"] else None
            elif source.get("source_utility"):
                # Every row is the source utility's, so its span is the table's.
                entry["utility_dimension"] = True
                span = {name: entry[name] for name in ("first", "last", "rows", "years")}
                entry["utilities"] = {source["source_utility"]: span} if entry["rows"] else {}
            else:
                entry["utility_dimension"] = False
                entry["utilities"] = {}
            datasets[key] = entry
    return {"$generated": GENERATED_NOTE, "datasets": datasets}


def write(conn: psycopg.Connection, path: Path = COVERAGE_PATH) -> dict[str, Any]:
    payload = measure(conn)
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print_step(f"dataset coverage → {path}")
    for key, entry in payload["datasets"].items():
        utilities = ", ".join(entry["utilities"]) or "no utility dimension"
        print(f"  {key}: {entry['first']} to {entry['last']} ({entry['rows']} rows; {utilities})")
    return payload


def main() -> int:
    conn = connect(get_settings())
    try:
        write(conn)
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
